//
// This file was generated by George
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://omegapoint.se/packagens", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sample.schema.two;
